quarkus.application.name=java-aws-serverless-messaging-lab
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:8088}
quarkus.smallrye-openapi.info-title=AWS Serverless Messaging Lab API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.micrometer.export.prometheus.path=/q/metrics
%prod.quarkus.log.console.json.enabled=true

aws.endpoint=${AWS_ENDPOINT:}
aws.region=${AWS_REGION:us-east-1}
aws.access-key=${AWS_ACCESS_KEY_ID:}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.sqs.queue-url=${COMMAND_QUEUE_URL:http://localhost:4566/000000000000/processing-commands}
aws.sqs.dlq-url=${COMMAND_DLQ_URL:http://localhost:4566/000000000000/processing-commands-dlq}
aws.dynamodb.table=${PROCESSING_TABLE:processing-state}
commands.worker.interval=${WORKER_INTERVAL:1s}

%test.aws.endpoint=http://localhost:4566
%test.aws.sqs.queue-url=http://localhost:4566/000000000000/test-commands
%test.aws.sqs.dlq-url=http://localhost:4566/000000000000/test-dlq
%test.aws.dynamodb.table=test-processing-state
%test.quarkus.scheduler.enabled=false
